name: Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/jgimillo/corec.git
          mkdocs gh-deploy --force --remote-branch gh-pages --remote-name origin --config-file docs/mkdocs.yml
